### 1. CREATE NOTE - SUCCESS
POST http://localhost:8080/api/notes
Content-Type: application/json

{
  "title": "Note 2 details: Kafka",
  "content": "Today I started learning Spring Boot architecture by building BrieflyAI."
}

### 2. GET ALL NOTES - SUCCESS
GET http://localhost:8080/api/notes

### 3. GET NOTE BY ID - SUCCESS
GET http://localhost:8080/api/notes/1

### 4. GET NOTE BY ID - NOT FOUND
GET http://localhost:8080/api/notes/999

### 5. CREATE NOTE - VALIDATION ERROR
POST http://localhost:8080/api/notes
Content-Type: application/json

{
  "title": "",
  "content": ""
}

### 6. CREATE NOTE - TITLE TOO LONG
POST http://localhost:8080/api/notes
Content-Type: application/json

{
  "title": "This title is intentionally made very long so that it can be used to verify that our @Size validation works correctly when the title exceeds the allowed maximum length configured in the request DTO. This should fail validation.",
  "content": "Testing title length validation."
}

### 7. CREATE NOTE + AI SUMMARY - SUCCESS
POST http://localhost:8080/api/notes
Content-Type: application/json

{
  "title": "Kafka Architecture",
  "content": "Apache Kafka is an event streaming platform used for asynchronous communication between applications. Producers publish messages to topics. Topics are divided into partitions for scalability. Consumers read messages from those partitions. Consumer groups allow multiple consumers to share the processing workload. Kafka stores messages for a configured retention period, which allows consumers to replay events when required."
}